using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace amp.anubis.client.security
{
    /// <summary>
    /// Represents an authenticated user who has been assigned 
    /// a session token.
    /// </summary>
    public class NamedToken
    {
        /// <summary>
        /// The identity of the user, generally represented by a Distinguished Name in LDAP
        /// </summary>
        public string Identity { get; set; }
        
        /// <summary>
        /// The session token generated by Anubis indicating that the user has successfully
        /// authenticated with the identity provided
        /// </summary>
        public string Token { get; set; }

        public NamedToken(string identity, string token)
        {
            Identity = identity;
            Token = token;
        }
    }

}
